### ISSUE TITLE
Gust Strength is missing

### ISSUE THREAD

**Issue by Shizzlebix** [exzz/netatmo-api-go#3]
Hello,

as i see Gust Strength is missing..

is this line correct:

        GustStrength     *int32   `json:"GustStrengthfloat32,omitempty"`

?

or better this:
        GustStrength     *int32   `json:"GustStrength,omitempty"`
?

**Comment by exzz** [comment]
Hi,

Thanks for reporting the typo. This has been fixed with dd616c37cf93536b4efd736983c58bba990c9a50
